### ISSUE TITLE
Server crash at launch not sure what the issue is but here's my log!

### ISSUE THREAD

**Issue by epicminerbackup** [hsyyid/SpongyChest#7]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.0-56.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.1.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.55-beta.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.82-universal.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.1.8.79-universal.jar)
  MalisisCorePlugin (malisiscore-1.9.4-4.1.1.jar)
  LoadingPlugin (Bloodmoon-MC1.9.4-1.4.1.jar)
  IC2core (industrialcraft-2-2.6.69-ex110.jar)
  AppleCore (AppleCore-mc1.10.2-2.0.1.jar)
  SpongeCoremod (spongeforge-1.10.2-2092-5.0.0-BETA-1753.jar)
  CCCDeobfPlugin (unknown)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  DepLoader (BrandonsCore-1.10.2-2.1.0.44-universal.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.73-universal.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.1.319.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 9/26/16 1:06 AM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchMethodError: org.spongepowered.api.data.key.KeyFactory.makeSingleKey(Ljava/lang/Class;Ljava/lang/Class;Lorg/spongepowered/api/data/DataQuery;)Lorg/spongepowered/api/data/key/Key;
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:576)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.spongepowered.api.data.key.KeyFactory.makeSingleKey(Ljava/lang/Class;Ljava/lang/Class;Lorg/spongepowered/api/data/DataQuery;)Lorg/spongepowered/api/data/key/Key;
    at io.github.hsyyid.spongychest.SpongyChest.<clinit>(SpongyChest.java:64)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at org.spongepowered.mod.plugin.SpongeModPluginContainer.constructMod(SpongeModPluginContainer.java:284)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.redirect$onPost$0(LoadController.java:53)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:545)
    ... 5 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 2455471008 bytes (2341 MB) / 2988507136 bytes (2850 MB) up to 15440281600 bytes (14725 MB)
    JVM Flags: 17 total; -Xmx15500M -Xms3000M -XX:+DisableExplicitGC -XX:NewRatio=3 -XX:SurvivorRatio=3 -XX:TargetSurvivorRatio=80 -XX:MaxTenuringThreshold=8 -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:MaxGCMinorPauseMillis=7 -XX:+ExplicitGCInvokesConcurrent -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=60 -XX:+BindGCTaskThreadsToCPUs -Xnoclassgc
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.1.2094 166 mods loaded, 166 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UC  mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UC  FML{8.0.99.99} [Forge Mod Loader] (forge.jar) 
    UC  Forge{12.18.1.2094} [Minecraft Forge] (forge.jar) 
    UC  CodeChickenCore{2.1.8.79} [CodeChicken Core] (minecraft.jar) 
    UC  OpenComputers|Core{1.6.0.3-rc.1} [OpenComputers (Core)] (minecraft.jar) 
    UC  spongeapi{5.0.0-SNAPSHOT-a01e398} [SpongeAPI] (minecraft.jar) 
    UC  sponge{1.10.2-2092-5.0.0-BETA-1753} [SpongeForge] (spongeforge-1.10.2-2092-5.0.0-BETA-1753.jar) 
    UC  ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.0.1.jar) 
    UC  mantle{1.10.2-1.0.0.jenkins170} [Mantle] (Mantle-1.10.2-1.0.0.jar) 
    UC  tconstruct{1.10.2-2.5.2.jenkins352} [Tinkers' Construct] (TConstruct-1.10.2-2.5.2.jar) 
    UC  immersiveengineering{0.10-42} [Immersive Engineering] (ImmersiveEngineering-0.10-42.jar) 
    UC  JEI{3.10.0.267} [Just Enough Items] (jei_1.10.2-3.10.0.267.jar) 
    UC  abyssalcraft{1.9.3-pre-1} [AbyssalCraft] (AbyssalCraft-1.10.2-1.9.3-pre-1.jar) 
    UC  actuallyadditions{1.10.2-r63} [Actually Additions] (ActuallyAdditions-1.10.2-r63.jar) 
    UC  AppleCore{2.0.1} [AppleCore] (AppleCore-mc1.10.2-2.0.1.jar) 
    UC  appleskin{1.0.4} [AppleSkin] (AppleSkin-mc1.10.2-1.0.4.jar) 
    UC  architecturecraft{1.5.0.0} [ArchitectureCraft] (ArchitectureCraft-1.5.0.0-mc1.10.2.jar) 
    UC  tesla{1.2.1.49} [TESLA] (Tesla-1.10.2-1.2.1.49.jar) 
    UC  thedragoncore{1.10.2-1.0.2.0} [TheDragonCore] (thedragoncore-1.10.2-1.0.2.0.jar) 
    UC  armorplus{1.10.2-7.0.0.0} [ArmorPlus] (armorplus-1.10.2-7.0.0.0.jar) 
    UC  autopackager{1.6.3} [AutoPackager] (autopackager-1.6.3.jar) 
    UC  Morphtool{1.0-11} [Morph-o-Tool] (Morph-o-Tool-1.0-11.jar) 
    UC  Psi{r1.0-39} [Psi] (Psi-r1.0-39.jar) 
    UC  Quark{r1.0-56} [Quark] (Quark-r1.0-56.jar) 
    UC  AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
    UC  bagginses{2.4.2d} [Bagginses] (Bagginses-1.10.2-3.0.4b.jar) 
    UC  Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
    UC  BBG{5.0.0} [BetterBedrockGen] (BBG-1.9.4-5.0.0.jar) 
    UC  bdlib{1.12.2.12} [BD Lib] (bdlib-1.12.2.12-mc1.10.2.jar) 
    UC  betteragriculture{0.16} [Better Agriculture] (BetterAgriculture_(MC-1.10)-0.16.jar) 
    UC  BiomesOPlenty{5.0.0.2085} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2085-universal.jar) 
    UC  guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
    UC  BloodMagic{1.9.4-2.1.0-63} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.1.0-63.jar) 
    UC  Bloodmoon{1.2} [Bloodmoon] (Bloodmoon-MC1.9.4-1.4.1.jar) 
    UC  bookshelf{1.4.1.319} [Bookshelf] (Bookshelf-1.10.2-1.4.1.319.jar) 
    UC  Botania{r1.9-323} [Botania] (Botania r1.9-323.jar) 
    UC  brandonscore{2.1.0} [Brandon's Core] (BrandonsCore-1.10.2-2.1.0.44-universal.jar) 
    UC  Bullseye{1.0.3} [Bullseye] (Bullseye-1.9.4-1.0.3.jar) 
    UC  Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
    UC  SonarCore{3.1.5} [SonarCore] (SonarCore-1.9.4-3.1.5.jar) 
    UC  Calculator{3.1.2} [Calculator] (Calculator-1.9.4-3.1.2.jar) 
    UC  Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
    UC  mcmultipart{1.2.1} [MCMultiPart] (MCMultiPart-1.2.1-universal.jar) 
    UC  CharsetLib{0.3.0-pre15} [???] (Charset-0.3.0-pre15.jar) 
    UC  CharsetAudio{0.3.0-pre15} [???] (Charset-0.3.0-pre15.jar) 
    UC  CharsetCarts{0.3.0-pre15} [U] (Charset-0.3.0-pre15.jar) 
    UC  CharsetDecoration{0.3.0-pre15} [???] (Charset-0.3.0-pre15.jar) 
    UC  CharsetDrama{0.3.0-pre15} [!] (Charset-0.3.0-pre15.jar) 
    UC  CharsetFarming{0.3.0-pre15} [;] (Charset-0.3.0-pre15.jar) 
    UC  CharsetGates{0.3.0-pre15} [&] (Charset-0.3.0-pre15.jar) 
    UC  CharsetPipes{0.3.0-pre15} [|] (Charset-0.3.0-pre15.jar) 
    UC  CharsetStorage{0.3.0-pre15} [#] (Charset-0.3.0-pre15.jar) 
    UC  CharsetTweaks{0.3.0-pre15} [*] (Charset-0.3.0-pre15.jar) 
    UC  CharsetWires{0.3.0-pre15} [+] (Charset-0.3.0-pre15.jar) 
    UC  CharsetWrench{0.3.0-pre15} [/] (Charset-0.3.0-pre15.jar) 
    UC  ChickenChunks{2.1.3.36} [ChickenChunks] (ChickenChunks-1.10.2-2.1.3.36-universal.jar) 
    UC  chisel{MC1.9.4-0.0.6.46} [Chisel] (Chisel-MC1.9.4-0.0.6.46.jar) 
    UC  chiselsandbits{12.1} [Chisels & Bits] (chiselsandbits-12.1.jar) 
    UC  IC2{2.6.69-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.69-ex110.jar) 
    UC  CompactSolars{5.0.4.328} [Compact Solar Arrays] (CompactSolars-1.10.2-5.0.4.328-universal.jar) 
    UC  cookingforblockheads{4.2.15} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.15.jar) 
    UC  correlatedpotentialistics{2.0.0-alpha2} [Correlated Potentialistics] (CorrelatedPotentialistics-2.0.0-alpha2.jar) 
    UC  craftingtweaks{6.1.14} [Crafting Tweaks] (CraftingTweaks_1.10.2-6.1.14.jar) 
    UC  MineTweaker3{3.0.11} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.11.jar) 
    UC  crossroads{1.10.2-1.1.4} [Crossroads] (crossroads-1.10.2-1.1.4.jar) 
    UC  cyberware{beta-0.2.2} [Cyberware] (cyberware-1.9.4-1.10.2-beta-0.2.2.jar) 
    UC  darkutils{1.1.4.76} [Dark Utilities] (DarkUtilities-1.10.2-1.1.4.85.jar) 
    UC  forestry{5.2.12.257} [Forestry] (forestry_1.10.2-5.2.12.257.jar) 
    UC  ElecCore{1.5.311} [ElecCore] (ElecCore-1.9.4-1.5.311.jar) 
    UC  EnderStorage{2.1.3.76} [EnderStorage] (EnderStorage-1.10.2-2.1.3.76-universal.jar) 
    UC  OpenComputers{1.6.0.3-rc.1} [OpenComputers] (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar) 
    UC  deepresonance{1.2.4} [DeepResonance] (deepresonance-1.10-1.2.4.jar) 
    UC  draconicevolution{2.0.0} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.0.100-universal.jar) 
    UC  easyBreeding{5.0.0} [Easy Breeding] (easybreeding-1.9.4-4.0.1.jar) 
    UC  economylite{2.2.6} [EconomyLite] (EconomyLite-5.0.0-2.2.6.jar) 
    UC  EnderBags{2.0.1} [EnderBags] (EnderBags-1.9.4-2.0.0.jar) 
    UC  endercore{1.10.2-0.4.1.55-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.55-beta.jar) 
    UC  EnderIO{1.10.2-3.0.1.112_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.112_beta.jar) 
    UC  shetiphiancore{3.3.1} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.1.jar) 
    UC  endertanks{1.4.2} [EnderTanks] (endertanks-1.10.0-1.4.2.jar) 
    UC  enderthing{0.6.11} [Enderthing] (enderthing-1.10.2-0.6.11.jar) 
    UC  EnderZoo{1.10-1.2.3.43} [Ender Zoo] (EnderZoo-1.10-1.2.3.43.jar) 
    UC  endmetals{1.0.4} [End Metals] (EndMetals_1.9-1.0.4.jar) 
    UC  valkyrielib{1.10.2-0.10.4} [Valkyrie Lib] (valkyrielib-1.10.2-0.10.4b.jar) 
    UC  environmentaltech{1.10.2-0.10.4b} [Environmental Tech] (environmentaltech-1.10.2-0.10.4b.jar) 
    UC  io.github.hsyyid.essentialcmds{@project.informativeVersion@} [EssentialCmds] (EssentialCmds-1.10.2-8.1.14-universal.jar) 
    UC  shadowmc{3.4.5} [ShadowMC] (ShadowMC-1.10.2-3.4.5.jar) 
    UC  ExtraRails{1.1.1} [Extra Rails] (ExtraRails-1.10.2-1.1.1.jar) 
    UC  zerocore{1.10.2-0.0.8.0} [Zero CORE] (zerocore-1.10.2-0.0.8.0.jar) 
    UC  bigreactors{0.4.5.15} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.15.jar) 
    UC  FastLeaveDecay{1.1} [Fast Leave Decay] (FastLeaveDecay-MC1.10.2-1.2.2.jar) 
    UC  flatcoloredblocks{mc1.10-v4.1} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.1.jar) 
    UC  ftbl{2.1.0} [FTBLib] (FTBLib-1.9.4-2.1.0-pre3.jar) 
    UC  ftbu{2.1.0} [FTBUtilities] (FTBUtilities-1.9.4-2.1.0-pre3.jar) 
    UC  gendustry{1.6.4.21} [GenDustry] (gendustry-1.6.4.21-mc1.10.2.jar) 
    UC  pressure{1.3.1.14} [Pressure Pipes] (pressure-1.3.1.14-mc1.10.2.jar) 
    UC  advgenerators{0.9.20.14} [Advanced Generators] (generators-0.9.20.14-mc1.10.2.jar) 
    UC  fishing{1.4.4} [Fishing Net Mod] (GiacomosFishingNet1.10.2-1.4.4.jar) 
    UC  grapple_hooks{1.0.8} [Grapple Hooks] (Grapple-Hooks-1.10.2-1.0.8.jar) 
    UC  InfernalMobs{1.7.1} [Infernal Mobs] (InfernalMobs-1.10.jar) 
    UC  inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
    UC  ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
    UC  JEFB{1.0.3} [Just Enough Forestry Bees] (jefb_1.10.2-1.0.3.jar) 
    UC  journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
    UC  je_calculation{1.10.2-2.0.3} [Just Enough Calculation] (JustEnoughCalculation-1.10.2-2.0.3.jar) 
    UC  login_shield{1.10.2-11-gb29eaad} [Login Shield] (Login_Shield-1.10.2-11-gb29eaad.jar) 
    UC  malisiscore{1.9.4-4.1.1} [MalisisCore] (malisiscore-1.9.4-4.1.1.jar) 
    UC  malisisblocks{1.9.4-4.0.1} [Malisis Blocks] (malisisblocks-1.9.4-4.0.1.jar) 
    UC  malisisdoors{1.9.4-5.0.4} [MalisisDoors] (malisisdoors-1.9.4-5.0.4.jar) 
    UC  Mekanism{9.2.1} [Mekanism] (MekanismAll-1102-921homebaked.jar) 
    UC  MekanismGenerators{9.2.1} [MekanismGenerators] (MekanismAll-1102-921homebaked.jar) 
    UC  MekanismTools{9.2.1} [MekanismTools] (MekanismAll-1102-921homebaked.jar) 
    UC  testdummy{1.11} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.11.jar) 
    UC  mobtotems{1.10.2-0.1.2} [Mob Totems] (mobtotems-1.10.2-0.1.2.jar) 
    UC  morebees{1.10.2-1.1.3} [More Bees] (morebees-1.10.2-1.1.3.jar) 
    UC  Morpheus{1.10.2-3.1.7} [Morpheus] (Morpheus-1.10.2-3.1.7.jar) 
    UC  NashornLib{1.9.4-1.8.77-1.3.1} [Nashorn Library] (NashornLib-1.9.4-1.8.77-1.3.1.8.jar) 
    UC  botanicaladdons{GRADLE:VERSION.GRADLE:BUILD} [Natural Pledge] (NaturalPledge-r1.5.jar) 
    UC  nethermetals{1.1.2} [Nether Metals] (NetherMetals_1.9-1.1.2.jar) 
    UC  netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
    UC  nmsot{1.1.7-mc[1.9.4-1.10.2]} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.1.7-mc[1.9.4-1.10.2].jar) 
    UC  recipehandler{0.5} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.5(1.10.2).jar) 
    UC  notenoughwands{1.3.7} [Not Enough Wands] (notenoughwands-1.10-1.3.7.jar) 
    UC  nucleus{0.9.0-5.0} [Nucleus] (Nucleus-0.9.0-S5-1.10.2-plugin.jar) 
    UC  fodc{1.9.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.9.1.jar) 
    UC  orespawn{1.1.0} [Ore Spawn] (OreSpawn_1.10.2-1.1.0.jar) 
    UC  packingtape{0.6.0} [Packing Tape] (PackingTape-1.10.2-0.6.0.jar) 
    UC  harvestcraft{1.9.4-1.10.2d} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2d.jar) 
    UC  ninja.leaping.permissionsex{2.0-SNAPSHOT-b141} [PermissionsEx] (PermissionsEx-Sponge.jar) 
    UC  platforms{1.2.0} [Platforms] (platforms-1.10.0-1.2.0.jar) 
    UC  prism{3.0.0} [Prism] (Prism-3.0.0-beta2-14-g154e2b2-all.jar) 
    UC  progressiveautomation{1.6.51} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.51.jar) 
    UC  com.gmail.trentech.pjp{0.11.4} [Project Portals] (projectportals-4.2.0-0.11.4.jar) 
    UC  pjw{0.10.4} [ProjectWorlds] (projectworlds-5.0.0-0.10.4.jar) 
    UC  psionup{GRADLE:VERSION.GRADLE:BUILD} [PSIonic Upgrades] (PSIonicUpgrades-r1.14.jar) 
    UC  randomthings{3.7.5} [Random Things] (RandomThings-MC1.10.2-3.7.5.jar) 
    UC  reborncore{2.7.2.41} [RebornCore] (RebornCore-1.10.2-2.7.2.41-universal.jar) 
    UC  reborncore-mcmultipart{2.7.2.41} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.7.2.41-universal.jar) 
    UC  br.net.fabiozumbi12.redprotect{6.5.0} [RedProtect] (RedProtect_Sponge-6.5.0-b206.jar) 
    UC  StorageDrawers{1.10.2-3.2.7} [Storage Drawers] (StorageDrawers-1.10.2-3.2.7.jar) 
    UC  refinedstorage{1.0.5} [Refined Storage] (refinedstorage-1.0.5.jar) 
    UC  xreliquary{1.10.2-1.3.3.543} [Reliquary] (Reliquary-1.10.2-1.3.3.543.jar) 
    UC  rftools{5.24} [RFTools] (rftools-1.10-5.24.jar) 
    UC  rftoolsdim{4.30beta50} [RFTools Dimensions] (rftoolsdim-1.10-4.30beta50.jar) 
    UC  Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
    UC  roots{0.202} [Roots] (roots-1.10.2-0.202.0.jar) 
    UC  servershops{1.1.0} [Server Shops] (ServerShops-1.10.2-1.1.0.jar) 
    UC  Signals{1.0} [Signals] (Signals-1.10.2-0.4.3-universal.jar) 
    UC  simpleretrogen{4.0.1+8} [Simple Retrogen] (simpleretrogen-1.10-4.0.1+8.jar) 
    UC  SleepingBag{1.2.1} [Sleeping Bag] (SleepingBag-1.9.4-1.2.1.jar) 
    UC  soulshardstow{1.10.2-2.6.3-43} [Soul Shards - The Old Ways] (SoulShards-TOW-1.10.2-2.6.3-43.jar) 
    UC  SpiceOfLife{1.3.4} [The Spice of Life] (SpiceOfLife-mc1.9.4-1.3.4.jar) 
    UE  io.github.hsyyid.spongychest{0.4.7} [SpongyChest] (SpongyChest-1.10.2-0.4.7-universal.jar) 
    UC  substratum{1.8.1.0} [Substratum] (Substratum-1.10.2-1.8.1.0.jar) 
    UC  techreborn{1.4.4.54} [TechReborn] (TechReborn-1.10.2-1.4.4.54-universal.jar) 
    UC  theoneprobe{1.1.2} [The One Probe] (theoneprobe-1.10-1.1.2.jar) 
    UC  tombmanygraves{1.10.2-2.1.10} [Tomb Many Graves] (TombManyGraves-1.10.2-2.1.10.jar) 
    UC  Translocator{2.1.2.29} [Translocator] (Translocators-1.10.2-2.1.2.29-universal.jar) 
    UC  voxelsniper{8.0.0} [VoxelSniper] (VoxelSniper-8.0.0-SNAPSHOT.jar) 
    UC  waterstrainer{1.3.0} [Water Strainer] (WaterStrainer-1.9.4-1.3.0.jar) 
    UC  icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.0.206.jar) 
    UC  wawla{2.3.0.202} [What Are We Looking At] (Wawla-1.10.2-2.3.0.206.jar) 
    UC  worldedit{6.1.5-SNAPSHOT} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.5-SNAPSHOT-dist (1).jar) 
    UC  wtfcore{1.10_BetaX} [wtfcore] (WTF_Expedition_1.10.2_Beta13.jar) 
    UC  xprings{1.2.0} [Experience Rings] (xprings-1.2.0.jar) 
    UC  UniDict{1.10.2-1.8c} [UniDict] (UniDict-1.10.2-1.8c.jar) 
    Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.0-56.jar)
  vazkii.quark.base.asm.ClassTransformer
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.1.jar)
  shetiphian.core.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.55-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.82-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.1.8.79-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
MalisisCorePlugin (malisiscore-1.9.4-4.1.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
LoadingPlugin (Bloodmoon-MC1.9.4-1.4.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
IC2core (industrialcraft-2-2.6.69-ex110.jar)

AppleCore (AppleCore-mc1.10.2-2.0.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
SpongeCoremod (spongeforge-1.10.2-2092-5.0.0-BETA-1753.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
CCCDeobfPlugin (unknown)

FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
DepLoader (BrandonsCore-1.10.2-2.1.0.44-universal.jar)

TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  li.cil.oc.common.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
  lumien.randomthings.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.73-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.1.319.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerHarvestTools (Enabled/Forced)
        - TinkerMeleeWeapons (Enabled/Forced)
        - TinkerRangedWeapons (Enabled/Forced)
        - TinkerModifiers (Enabled/Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - TinkerModelRegister (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)
        - craftingtweaksIntegration (Enabled/Not Forced)
        - WailaIntegration (Enabled/Not Forced)

    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
    Type: Dedicated Server (map_server.txt)
```

**Comment by cartman-2000** [comment]
This is due to the change in the api on how the custom data is handled, the plugin will need to be updated before it'll work on the newer versions of sponge.

**Comment by epicminerbackup** [comment]
A friend of mine updated it and it works greate now :)

**Comment by sleiss** [comment]
@epicminerbackup Is your friend sharing his changes somewhere?

**Comment by epicminerbackup** [comment]
I have a copy here if you want it

**Comment by sleiss** [comment]
I fixed it myself in the meantime.
