### ISSUE TITLE
Crashes under Spongeforge 1.10.2-2106-6.0.0-BETA-1840

### ISSUE THREAD

**Issue by wiesshund** [hsyyid/SpongyChest#8]
Posting crashlog below, although it may just be that it is in need of a more recent update?

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.10.2-2107-6.0.0-BETA-1840.jar)
  IC2core (industrialcraft-2-2.6.87-ex110.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 10/26/16 12:58 AM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchMethodError: org.spongepowered.api.data.key.KeyFactory.makeSingleKey(Ljava/lang/Class;Ljava/lang/Class;Lorg/spongepowered/api/data/DataQuery;)Lorg/spongepowered/api/data/key/Key;
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:580)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.spongepowered.api.data.key.KeyFactory.makeSingleKey(Ljava/lang/Class;Ljava/lang/Class;Lorg/spongepowered/api/data/DataQuery;)Lorg/spongepowered/api/data/key/Key;
    at io.github.hsyyid.spongychest.SpongyChest.<clinit>(SpongyChest.java:64)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at org.spongepowered.mod.plugin.SpongeModPluginContainer.constructMod(SpongeModPluginContainer.java:284)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzd000(LoadController.java:53)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:549)
    ... 5 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_101, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 389402848 bytes (371 MB) / 1096286208 bytes (1045 MB) up to 1908932608 bytes (1820 MB)
    JVM Flags: 2 total; -Xms512M -Xmx2G
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.2.2107 28 mods loaded, 28 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UC  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UC  FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.2.2107-universal.jar) 
    UC  Forge{12.18.2.2107} [Minecraft Forge](forge-1.10.2-12.18.2.2107-universal.jar) 
    UC  spongeapi{6.0.0-SNAPSHOT-cebc736} [SpongeAPI](minecraft.jar) 
    UC  sponge{1.10.2-2107-6.0.0-BETA-1840} [SpongeForge](spongeforge-1.10.2-2107-6.0.0-BETA-1840.jar) 
    UC  adminshop{1.8.2} [AdminShop](AdminShop-1.10.2-1.8.2-universal.jar) 
    UC  craftbook{4.0} [CraftBook](CraftBook-4.0-SNAPSHOT.jar) 
    UC  customspawner{3.10.1} [DrZhark's CustomSpawner](CustomMobSpawner 3.10.1.jar) 
    UC  mocreatures{10.0.6} [DrZhark's Mo'Creatures Mod](DrZhark's Mo'Creatures Mod-10.0.6.jar) 
    UC  dungeontactics{DT-0.10.5} [DungeonTactics](DungeonTactics-1.10.2-0.10.5.jar) 
    UC  economylite{2.2.7} [EconomyLite](EconomyLite-5.0.0-2.2.7.jar) 
    UC  endercore{1.10.2-0.4.1.56-beta} [EnderCore](EnderCore-1.10.2-0.4.1.56-beta.jar) 
    UC  EnderIO{1.10.2-3.0.1.120_beta} [Ender IO](EnderIO-1.10.2-3.0.1.120_beta.jar) 
    UC  io.github.hsyyid.essentialcmds{@project.informativeVersion@} [EssentialCmds](EssentialCmds-1.10.2-8.1.14-universal.jar) 
    UC  flexiblelogin{0.8} [FlexibleLogin](FlexibleLogin.jar) 
    UC  foxcore{0.9.4-156} [FoxCore](FoxCore-0.9.4-156-server.jar) 
    UC  foxguard{0.19.3-dev-318} [FoxGuard](FoxGuard-0.19.3-dev-318.jar) 
    UC  simplecore{1.3.11.0} [SimpleCore API](simplecore-1.10.2-1.3.11.0.jar) 
    UC  simpleores{1.8.5.3} [SimpleOres 2](simpleores-1.10.2-1.8.5.3.jar) 
    UC  netherrocks{1.4.1.1} [Netherrocks](netherrocks-1.10.2-1.4.1.1.jar) 
    UC  fusion{2.1.3.3} [Fusion](fusion-1.10.2-2.1.3.3.jar) 
    UC  IC2{2.6.87-ex110} [IndustrialCraft 2](industrialcraft-2-2.6.87-ex110.jar) 
    UC  nbtedit{$version} [NBTEdit](NBTEdit-0.2.jar) 
    UC  netherportalfix{1.0} [Nether Portal Fix](netherportalfix-mc1.9.4-4.0.1.jar) 
    UC  permissionsex{2.0-SNAPSHOT-b145} [PermissionsEx](PermissionsEx-Sponge.jar) 
    UC  pjp{0.13.2} [ProjectPortals](projectportals-5.0.0-0.13.2.jar) 
    UE  io.github.hsyyid.spongychest{0.4.7} [SpongyChest](SpongyChest-1.10.2-0.4.7-universal.jar) 
    UC  worldedit{6.1.4} [WorldEdit](worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
    Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.10.2-2107-6.0.0-BETA-1840.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
IC2core (industrialcraft-2-2.6.87-ex110.jar)

EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
    Type: Dedicated Server (map_server.txt)`
```

**Comment by ProsperCraft** [comment]
Same - https://gist.github.com/ProsperCraft/307422aefdc96c7373988cbe3111d416

```
SpongeAPI: 6.0.0-SNAPSHOT-bd88c91                                                                                                                                            │···········································································
SpongeForge: 1.10.2-2107-6.0.0-BETA-1869                                                                                                                                     │···········································································
Minecraft Forge: 12.18.2.2120  
```
